name: build & run tests

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set up dune
        uses: ocaml-dune/setup-dune@v2.1.0
        with:
          version: 3.23.1
          steps: install-dune enable-pkg lazy-update-depexts install-gpatch install-depexts build-deps

      - run: dune tool install ocamlformat

      - run: dune build

      - run: dune runtest

      - run: dune fmt
